function Hd = stopbandfilter
%STOPBANDFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 06-Apr-2021 11:59:52

% FIR Window Bandstop filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 64;  % Sampling Frequency

N    = 100;      % Order
Fc1  = 0.1;      % First Cutoff Frequency
Fc2  = 1;        % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'stop', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
